APPIMAGE = dict(
    LOGO_LIGHT_SVG="logo_light.svg",
    LOGO_DARK_SVG ="logo_dark.svg",
    LOGO_LIGHT_PNG="logo_light.png",
    LOGO_DARK_PNG ="logo_dark.png",

    ICON_SVG    ="icon.svg",
    ICON_PNG_16 ="icon_16x16.png",
    ICON_PNG_32 ="icon_32x32.png",
    ICON_PNG_64 ="icon_64x64.png",
    ICON_PNG_128="icon_128x128.png",
    ICON_PNG_256="icon_256x256.png",
    ICON_ICO_256="icon_256x256.ico",

    NEW_DARK_PNG   ="new_dark.png",
    NEW_LIGHT_PNG  ="new_light.png",
    OPEN_DARK_PNG  ="open_dark.png",
    OPEN_LIGHT_PNG ="open_light.png",
    ADD_DARK_PNG   ="add_dark.png",
    ADD_LIGHT_PNG  ="add_light.png",
    SET_DARK_PNG   ="set_dark.png",
    SET_LIGHT_PNG  ="set_light.png",
    NEW_PROJECT_PNG="new_project.png",

    HAND_DARK_PNG          ="hand_dark.png",
    HAND_LIGHT_PNG         ="hand_light.png",
    SELECT_DARK_PNG        ="select_dark.png",
    SELECT_LIGHT_PNG       ="select_light.png",
    CUT_DARK_PNG           ="cut_dark.png",
    CUT_LIGHT_PNG          ="cut_light.png",
    PAUSE_DARK_PNG         ="pause_dark.png",
    PAUSE_LIGHT_PNG        ="pause_light.png",
    PLAY_DARK_PNG          ="play_dark.png",
    PLAY_LIGHT_PNG         ="play_light.png",
    PLAY_TO_LEFT_DARK_PNG  ="play_to_left_dark.png",
    PLAY_TO_LEFT_LIGHT_PNG ="play_to_left_light.png",
    PLAY_TO_RIGHT_DARK_PNG ="play_to_right_dark.png",
    PLAY_TO_RIGHT_LIGHT_PNG="play_to_right_light.png",
    BACKWARD_DARK_PNG      ="backward_dark.png",
    BACKWARD_LIGHT_PNG     ="backward_light.png",
    FORWARD_DARK_PNG       ="forward_dark.png",
    FORWARD_LIGHT_PNG      ="forward_light.png",
)
